title: HL7 Portugal
email: geral@hl7.pt
description: >-
  HL7 Portugal é a associação portuguesa dedicada à interoperabilidade em saúde
  com padrões abertos HL7, FHIR e afins. Formação, recursos e comunidade.
baseurl: ""
url: "https://hl7-pt.github.io"
logo: /assets/images/og-default.svg
lang: pt-PT
timezone: Europe/Lisbon

twitter:
  username: hl7portugal

author:
  name: HL7 Portugal

social:
  name: HL7 Portugal
  links:
    - https://www.linkedin.com/company/hl7-portugal

markdown: kramdown
highlighter: rouge
permalink: /noticias/:title/

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  recursos:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
